export const GETTING_PROFILE = 'GETTING_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const UPDATING_PROFILE = 'UPDATING_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATING_PASSWORD = 'UPDATING_PASSWORD'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const UPDATING_AVATAR = 'UPDATING_AVATAR'
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS'
export const UPDATE_AVATAR_FAIL = 'UPDATE_AVATAR_FAIL'

export const DELETING_AVATAR = 'DELETING_AVATAR'
export const DELETE_AVATAR_SUCCESS = 'DELETE_AVATAR_SUCCESS'
export const DELETE_AVATAR_FAIL = 'DELETE_AVATAR_FAIL'